# Perons API rest endpoints
# All persons
GET http://localhost:3001/api/persons

###
# Person API info page
GET http://localhost:3001/api/persons/info

###
# Person by id
GET http://localhost:3001/api/persons/61a20b54b81aae8e7750ea77

###
# Delete person by id
DELETE http://localhost:3001/api/persons/1

###
# Create new person
POST http://localhost:3001/api/persons
content-type: application/json

{
    "name": "Anmol Gupta",
    "number": "12-31-232021"
}

###
# Update person
PUT http://localhost:3001/api/persons/61a227ecaa19637ad27aa83f
content-type: application/json

{
    "name": "AG",
    "number": "22-11-333444"
}
