# GET ALL Request
GET http://localhost:3001/api/blogs

###

# Create new entry
POST http://localhost:3001/api/blogs
content-type: application/json
#Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFubW9sZ3VwdGEiLCJpZCI6IjYxYTg0MzljYjc4NzUzZGVkNmEzY2NjYiIsImlhdCI6MTYzODQyNDEyNSwiZXhwIjoxNjM4NDI3NzI1fQ.FH2ha9bIzBVGpDY4bdU83RQ1vI6gl-w-PzlyACAfGH4
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFubW9sZ3VwdGEyIiwiaWQiOiI2MWE4NjExZWFkN2JjYzc1NDRiOThhOWIiLCJpYXQiOjE2Mzg0MjQ4NzgsImV4cCI6MTYzODQyODQ3OH0.6r_AoXO5yd-RjbXf4vpET4kNdMCKru9kifbvv5UTZcc

{
  "title": "Blog by user 2",
  "likes": 10,
  "url": "http://a-blog-with-a-user-returns.html",
  "author": "Blog Author User 2"
}

###
# Blog by id
GET http://localhost:3001/api/blogs/61a2566723f9c8306bac7816

###
# Delete Blog by id
DELETE http://localhost:3001/api/blogs/61a8615bad7bcc7544b98aa1
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6ImFubW9sZ3VwdGEiLCJpZCI6IjYxYTg0MzljYjc4NzUzZGVkNmEzY2NjYiIsImlhdCI6MTYzODQyNDEyNSwiZXhwIjoxNjM4NDI3NzI1fQ.FH2ha9bIzBVGpDY4bdU83RQ1vI6gl-w-PzlyACAfGH4

###
# Update blog by id
PUT http://localhost:3001/api/blogs/61a2566c23f9c8306bac7819
content-type: application/json

{
  "title": "Hello world!",
  "author": "AG",
  "likes": 2,
  "url": "http//guptaanmol184.com"
}